DROP TABLE IF EXISTS CONTACT;
DROP TABLE IF EXISTS HOBBY;
DROP TABLE IF EXISTS PLACE;
DROP TABLE IF EXISTS MESSAGE;

CREATE TABLE CONTACT (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
  , FIRST_NAME VARCHAR (50) NOT NULL
  , LAST_NAME VARCHAR (99)
  , BIRTH_DATE DATE
);

CREATE TABLE HOBBY(
      ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
    , TITLE VARCHAR (99) NOT NULL
    , DESCRIPTION VARCHAR (250)
);

CREATE TABLE PLACE(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
  , TITLE VARCHAR (99) NOT NULL
  , DESCRIPTION VARCHAR (250)
  , LONGITUDE INT
  , LATITUDE INT
);

CREATE TABLE MESSAGE(
		ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
	, CONTACT_ID INT NOT NULL
	, CONTENT VARCHAR(1500) NOT NULL
	, DATE DATE
);

