DROP TABLE IF EXISTS CONTACT;
DROP TABLE IF EXISTS HOBBY;
DROP TABLE IF EXISTS PLACE;
DROP TABLE IF EXISTS CONTACT_HOBBIES;
DROP TABLE IF EXISTS CONTACT_PLACES;
DROP TABLE IF EXISTS LIST_FRIENDS;
DROP TABLE IF EXISTS MESSAGE;
DROP TABLE IF EXISTS CONTACT_MESSAGE;


CREATE TABLE CONTACT (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
  , FIRST_NAME VARCHAR (50) NOT NULL
  , LAST_NAME VARCHAR (99)
  , BIRTH_DATE DATE
);

CREATE TABLE HOBBY(
      ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
    , TITLE VARCHAR (99) NOT NULL
    , DESCRIPTION VARCHAR (250)
);

CREATE TABLE CONTACT_HOBBIES(
    CONTACT_ID INT NOT NULL
  , HOBBY_ID INT NOT NULL
);

CREATE TABLE PLACE(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
  , TITLE VARCHAR (99) NOT NULL
  , DESCRIPTION VARCHAR (250)
  , LONGITUDE INT
  , LATITUDE INT
);

CREATE TABLE CONTACT_PLACES(
    CONTACT_ID INT NOT NULL
  , PLACE_ID INT NOT NULL
);

CREATE TABLE MESSAGE(
		ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
	, CONTACT_ID INT NOT NULL
	, CONTENT VARCHAR(1500) NOT NULL
	, DATE DATE
);


CREATE TABLE LIST_FRIENDS(
    CONTACT_ID_ONE INT NOT NULL
  , CONTACT_ID_TWO INT NOT NULL
);

CREATE TABLE CONTACT_MESSAGE(
    CONTACT_ID INT NOT NULL
  , MESSAGE_ID INT NOT NULL
);